<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.XInput" Version="3.8.2" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
    <PackageReference Include="WinUSBNet" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appSettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
